### ISSUE TITLE
Incorrect path in the kubernetes directory

### ISSUE THREAD

**Issue by drfred1981** [cbirkenbeul/homelab#1407]
Hello
I think there is an incorrect path with ":" in the path : "kubernetes"
https://github.com/cbirkenbeul/homelab/tree/main/kubernetes
as if it was a resolved symlink

A a result this repo can not be checkout.

$ git clone https://github.com/cbirkenbeul/homelab
Cloning into 'homelab'...
remote: Enumerating objects: 32706, done.
remote: Counting objects: 100% (4966/4966), done.
remote: Compressing objects: 100% (2397/2397), done.
remote: Total 32706 (delta 2629), reused 4860 (delta 2533), pack-reused 27740 (from 1)
Receiving objects: 100% (32706/32706), 5.16 MiB | 12.61 MiB/s, done.
Resolving deltas: 100% (18449/18449), done.
error: invalid path 'kubernetes/main/bootstrap/talos/clusterconfig/talosconfig:/Users/teqqy/GitHub/homelab/kubernetes/utility/bootstrap/talos/clusterconfig/talosconfig'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

best regards

**Comment by cbirkenbeul** [comment]
Thanks. The kubernetes/main folder ist for a later cluster migration from the k3s-cluster folder. I've deleted the file, because its not needed at this time.
